dist: trusty

language: node_js

node_js:
  - node
  - 11

addons:
  sonarcloud:
    organization: diplomatiq
    token:
      secure: EJPDxF3dUfMjnn//vSJr9GmJpGHuYzar2+USKVP7C+WoVqwFUaYB2SqzD+x35ZGIWNs06VCT8ki8WoR0rwpDq7+DVgSUGcnf5qOM7LYFSA1IxDpJWZSd6f4qHBZIQLurE0p13N/wVv6u+sM8Z6vD5Ta+aI2+FzKEvsOLxRoqPaewUW40lilyYsufLh7LOA5aZWAOlag7nFU4n/MzGxKWtRXnGZmf0AaEZTfEyQcPkIpHVeeWQcCFAwKFVaYRauAV+X4VHw6NU+lIkyeLRf1g8PFnKP3PdWACm/8e6v5/PGfOYLTU5HTaQIo5VpPLhJqLUiyMS4h1GraLs3d+o1DA+Irmy3hcnEHQuFzyXwRUOAaBshYQjxgTMkOiv2/ZDgL0h8g2Y2fTbTTVgSu1895dKKO5hCpBCZ7aJ1ZaAl9yJacl6YlGi07DO8F6ffs6HaykJ5MtEZE4fO4Brq/2wfW4EXyL1dbp1xEpgI75JYS5QCTUHahhpc/u4VATxO5raKK9zZ+Lm1P6oePOX/OceD2Bl/kzgzMWQKFPemjleeZFloUnmAExhrFmMTMQCPIG6SMD/Y4AqtAVVaEelG1Osk/7Lk3HW1BvdUptg9l/rdFBFMDt+jhqIac/7ulZaIqE3gAXYbbYB/HWHEYxET6YxAWfQBRu6IbfGn8BjKYFdU7CF3Q=

install: npm ci

script:
  - commitlint-travis
  - npm run build-and-test-everything
  - sonar-scanner
